---
# tasks file for ansible-role-traefik
- name: Make sure working directory exist
  ansible.builtin.file:
    path: "{{ traefik_working_directory }}"
    state: directory

- name: Make sure config directory exist
  ansible.builtin.file:
    path: "{{ traefik_working_directory }}/config"
    state: directory

- name: Copy static files
  ansible.builtin.template:
    src: "{{ item }}.yml.j2"
    dest: "{{ traefik_working_directory }}/{{ item }}.yml"
    mode: "0600"
  with_items:
    - docker-compose
    - traefik

- name: Make sure acme.json files exists with correct permissions
  ansible.builtin.file:
    path: "{{ traefik_working_directory }}/{{ item }}.json"
    mode: "0600"
    state: touch
  with_items:
    - "acme-cf"
    - "acme-http"

- name: Copy dynamic config files
  ansible.builtin.template:
    src: "config/{{ item }}.yml.j2"
    dest: "{{ traefik_working_directory }}/config/{{ item }}.yml"
  with_items:
    - api
    - middlewares

- name: Make sure users.txt exists with correct permissions
  ansible.builtin.file:
    path: "{{ traefik_working_directory }}/config/users.txt"
    mode: "0600"
    state: touch

- name: Add dashboard users
  ansible.builtin.lineinfile:
    path: "{{ traefik_working_directory }}/config/users.txt"
    line: "{{ item }}"
    state: present
  with_items: 
    - "{{ traefik_api.users }}"
